# Language-specific settings

# pandoc-citeproc
reference-section-title: Literaturverzeichnis

# pandoc-crossref
figPrefix:
  - Abbildung
  - Abbildungen
eqnPrefix:
  - Gleichung
  - Gleichungen
tblPrefix:
  - Tabelle
  - Tabellen
lstPrefix:
  - Quellcode
  - Quellcode
secPrefix:
  - Abschnitt
  - Abschnitte
